version: "3"
services:
  backend:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "melofind"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: 